### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [madman-bob/python-custom-imports#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary custom-imports -w /tmp/ext custom-imports==1.0.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting custom-imports==1.0.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/cf5/bf1365f8f9e4f/custom_imports-1.0.0.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ndictiv9/custom-imports/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ndictiv9/custom-imports/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ndictiv9/custom-imports/pip-egg-info
         cwd: /tmp/pip-wheel-ndictiv9/custom-imports/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-ndictiv9/custom-imports/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
Human comment: I'm not sure exactly how you got the sdist that's up there; I see the setup.py in the subdir but this is a bit unusual.

**Comment by madman-bob** [comment]
The distribution is generated automatically using [pypi_upload/pypi_upload.sh](https://github.com/madman-bob/python-custom-imports/blob/master/pypi_upload/pypi_upload.sh) - nothing fancy is going on. The location of setup.py is non-standard but legitimate.

I'm not sure what action you're expecting from this.
